### ISSUE TITLE
Add a link to github in the top navigation bar

### ISSUE THREAD

**Issue by tomusdrw** [FluffyLabs/typeberry-toolkit#92]
Similarly to [GrayPaper reader](https://github.com/FluffyLabs/graypaper-reader) we should add a link back to the github repository in the top navigation bar.

<img width="883" alt="image" src="https://github.com/user-attachments/assets/315d7f5a-08ce-4fa9-a773-273bc8872350">

**Comment by piotrzwolinski** [comment]
Logos in svg / png
[github-mark-c791e9551fe4.zip](https://github.com/user-attachments/files/16706988/github-mark-c791e9551fe4.zip)

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/4c98361b-5024-41ef-830e-4f8892d8f489">
